buildscript {
    ext{
        compile_sdk_version = 34
        agp_version = '8.9.1'
        kotlin_version = '2.2.21'
        ksp_version = "2.2.21-2.0.5"
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$ksp_version"
        classpath "com.google.gms:google-services:4.4.2"
        classpath "de.undercouch:gradle-download-task:5.6.0"
        classpath "androidx.room:room-gradle-plugin:2.6.1"
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
